#!/bin/sh

set -e

plistdir=~/Library/LaunchAgents
plist="$plistdir"/macos-login-hook.login.d.plist

bindir=~/bin

mkdir -p ~/.login.d "$plistdir" "$bindir"

test -e "$plist" && { echo "$0: $plist exists, not overwriting" >&2; exit 2; }

script="$bindir"/loginhook
scrsrc=./loginhook
test -x "$scrsrc" || { echo "$0: $scrsrc is not executable, aborting" >&2; exit 3; }

cp -p "$scrsrc" "$script"

# Substantially based on https://stackoverflow.com/a/22872222/874188
cat <<: >"$plist"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>macos-login-hook.login.d</string>
    <key>ProgramArguments</key>
    <array>
        <string>$script</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
:

launchctl load "$plist"

cp -p esc-key ~/.login.d/

./loginhook
