#!/bin/sh

# Basically, reimplements https://unix.stackexchange.com/a/560404
# Before this can work, you need to run this command just once:
# ssh-add --apple-use-keychain /path/to/your/private_key

ssh-add --apple-load-keychain
