#!/bin/sh

set -e

for dir in $HOME/bin $HOME/.local/bin; do
    fgrep -q "$dir" /etc/paths.d/* && continue
    printf '%s\n' "$dir" >\
        /etc/paths.d/user-"$(echo "${dir#$HOME/}" | tr '/' '-')"
done
